/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 lotus.glb 
Author: theruletik (https://sketchfab.com/theruletik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotus-flower-blooming-animation-771bfb8b865d47ba96b1ebb333029cfd
Title: Lotus Flower Blooming Animation
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lotus.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.Animation.fadeIn(2);
    actions.Animation.play();
    
    
   }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0.9]} scale={0.29}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0.5, 0.9]}>
              <group name="Mesh_0001_0" position={[0.018, -0.033, -0.004]} rotation={[Math.PI, 0, 0.9]} scale={0.166}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['wire_135110008.002']} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['wire_145028177.005']} />
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['wire_145028177.005']} />
              </group>
              <group name="Mesh_47002_2" position={[0.361, 1.344, 1.042]} rotation={[-1.908, -0.019, -0.066]} scale={0.166}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_48002_3" position={[-0.488, 0.874, -0.092]} rotation={[-1.214, 1.036, -0.156]} scale={0.166}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_49002_4" position={[-0.964, 1.251, 0.445]} rotation={[-1.739, 0.381, 0.093]} scale={0.166}>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_50002_5" position={[0.858, 0.733, 0.376]} rotation={[-1.682, -0.842, -0.482]} scale={0.166}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_51002_6" position={[-0.603, 1.55, 0.829]} rotation={[-1.681, 0.059, 0.239]} scale={0.166}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_52002_7" position={[0.957, 1.513, -0.112]} rotation={[-1.543, -0.072, 0.014]} scale={0.166}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_53002_8" position={[-0.916, 1.265, 0.19]} rotation={[-Math.PI / 2, 0.595, 0]} scale={0.166}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_54002_9" position={[1.154, 1.281, -0.002]} rotation={[-1.557, -0.523, -0.125]} scale={0.166}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_55002_10" position={[-0.097, 1.415, -1.036]} rotation={[-1.424, 0.04, -0.047]} scale={0.166}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_56002_11" position={[0.536, 1.329, -0.603]} rotation={[-0.714, -0.734, 0.21]} scale={0.166}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_57002_12" position={[1.004, 1.223, -0.563]} rotation={[-1.309, -0.273, -0.051]} scale={0.166}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_58002_13" position={[-0.747, 1.488, -0.679]} rotation={[-1.498, 0.138, 0.131]} scale={0.166}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_59002_14" position={[1.016, 1.306, 0.437]} rotation={[-1.642, -0.326, 0.064]} scale={0.166}>
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_60002_15" position={[-0.988, 1.491, 0.149]} rotation={[-1.568, 0.128, 0.016]} scale={0.166}>
                <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_61002_16" position={[-0.353, 1.196, -1.266]} rotation={[-0.48, 0.014, -0.155]} scale={0.166}>
                <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_62002_17" position={[1.307, 1.175, -0.057]} rotation={[-1.589, -0.855, -0.04]} scale={0.166}>
                <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_63002_18" position={[0.885, 1.194, 0.761]} rotation={[-2.175, -0.573, -0.302]} scale={0.166}>
                <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_64002_19" position={[0.121, 1.145, 1.008]} rotation={[-2.314, -0.068, -0.201]} scale={0.166}>
                <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_65002_20" position={[-0.979, 1.207, -0.702]} rotation={[-0.853, 0.797, -0.216]} scale={0.166}>
                <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_66002_21" position={[-0.169, 1.237, -1.06]} rotation={[-0.909, 0.092, 0]} scale={0.166}>
                <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_67002_22" position={[0.732, 1.186, 1.02]} rotation={[-1.939, -0.322, -0.148]} scale={0.166}>
                <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_68002_23" position={[-0.976, 1.207, -0.769]} rotation={[-1.075, 0.452, -0.167]} scale={0.166}>
                <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_69002_24" position={[-0.729, 1.342, -1.065]} rotation={[-1.13, 0.284, -0.168]} scale={0.166}>
                <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_70002_25" position={[-0.045, 1.271, 1.341]} rotation={[-2.039, 0, 0]} scale={0.166}>
                <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_71002_26" position={[-0.447, 1.337, 1.067]} rotation={[-1.948, 0.02, 0.374]} scale={0.166}>
                <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_72002_27" position={[0.514, 1.446, 0.351]} rotation={[-2.353, -0.814, -0.526]} scale={0.166}>
                <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_73002_28" position={[-0.857, 1.279, 0.086]} rotation={[-1.571, 1.227, 0]} scale={0.166}>
                <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_74002_29" position={[-0.65, 1.256, 0.567]} rotation={[-2.232, 0.475, 0.148]} scale={0.166}>
                <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_75002_30" position={[0.729, 1.5, 0.769]} rotation={[-1.63, -0.086, -0.049]} scale={0.166}>
                <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_76002_31" position={[-0.374, 0.914, -0.419]} rotation={[-0.574, 0.404, -0.488]} scale={0.166}>
                <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_77002_32" position={[-0.899, 1.345, 0.636]} rotation={[-1.941, 0.461, 0.149]} scale={0.166}>
                <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_78002_33" position={[-0.279, 0.984, 0.472]} rotation={[-2.45, 0.103, 0.085]} scale={0.166}>
                <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_79002_34" position={[0.373, 1.278, -1.133]} rotation={[-1.091, 0.009, -0.005]} scale={0.166}>
                <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_80002_35" position={[0.416, 1.142, -1.12]} rotation={[-0.584, -0.15, 0.241]} scale={0.166}>
                <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_81002_36" position={[-1.444, 1.317, -0.274]} rotation={[-1.366, 0.423, -0.316]} scale={0.166}>
                <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_82002_37" position={[0.101, 1.513, 0.989]} rotation={[-1.737, 0.012, 0.205]} scale={0.166}>
                <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_83002_38" position={[0.902, 1.223, -0.862]} rotation={[-1.148, -0.44, -0.079]} scale={0.166}>
                <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials['wire_196088225.002']} />
              </group>
              <group name="Mesh_84002_39" position={[0.643, 1.498, -0.724]} rotation={[-1.443, -0.07, 0.058]} scale={0.166}>
                <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials['wire_196088225.002']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lotus.glb')
